# Generated by Django 5.0.3 on 2024-03-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0002_shape_fruit_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('fruits', models.ManyToManyField(related_name='recipes', to='graphql_app.fruit')),
            ],
        ),
    ]
